### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nimisha84** [ehalsey-quickbooks/QuickBooksASPNetCore2OpenIDConnect#2]
Excellent work Eric. Sorry, I got a bit delayed in testing out the sample app.
This is a really good sample app for .Net Core and OpenIdConnect for Intuit.
I will definitely get a reference to this repo from our docs.
But before that, I need some help from you to add some details in Read me-
1) Can you add a link to the source of https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet.
2) Provide a brief desc of how token and refresh token gen works or a link to the Microsoft specs should be also good.
3) Add some details around how Refresh token, Revoke token and User Info calls are being made using this lib.
One line should be fine or a reference to Microsoft is good too.

Please note that once we reference your github repo in our docs, multiple devs will benefit from it and may have questions for you in future. Let me know if that is ok with you.
Thanks again for the great work indeed. It is devs like you who help us build a great community.

Thanks,
Nimisha
Intuit Developer Group

**Comment by ehalsey** [comment]
Thanks Nimisha!  
For #1 to confirm, you would like me to add a reference to https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/master/src/Microsoft.IdentityModel.Protocols.OpenIdConnect even though it is part of .NET Core 2.  Dev's do not need to include this source they just need to ref the namespace.

**Comment by ehalsey** [comment]
@nimisha84 For items 2 & 3 the sample does not implement anything for refresh and revoke tokens.  The goal of this walk through is to show the min. required to make QBO API requests using OpenId Connect.  I have a complete solution that implements using refresh tokens, uses dependency injection and other best practices.  I do not currently have a write-up describing this solution.

**Comment by nimisha84** [comment]
Thanks Eric, is it possible for you to provide me a link to that solution for 2 and 3? I can help with the write up if I get some time.
For 1, I just wanted you to point the link in Appendix or docs. No need to add in solution.

**Comment by ehalsey** [comment]
Hi Nimisha,

The solution is currently in a private git repo.  Can I can email you a zipped copy of the source?

 

Regards,

Lion Eric

(657) 845-0703

**Comment by nimisha84** [comment]
Sure, send it to me on nimisha_shrivastava@intuit.com 
Thanks!

**Comment by jacobrillema** [comment]
Hi there, can you please post when the additional write up is done and where we can find it at? Thanks for your help!

**Comment by JohnCampionJr** [comment]
I would greatly appreciate help with the refresh tokens too.  Eric, if you'd like, I would be glad to pull out the refresh token code and submit a PR to this repo to help others.

**Comment by ehalsey** [comment]
Hi @JohnCampionJr,
I'm all for anything to help other devs.  Do you need anything on my end?

**Comment by JohnCampionJr** [comment]
If you want to send me the code that you can from the private repo, I was offering to update this project with just the refresh token code so as to both learn myself and help others :)

**Comment by ehalsey** [comment]
Hi John,

You can find the code at the following link

https://drive.google.com/file/d/0ByNv86o88hPaR3pZTDRXdmsyc1E/view

**Comment by JohnCampionJr** [comment]
Confirming receipt; if you want to delete that code, I have it now.

**Comment by MohitSingh1001** [comment]
@nimisha84  hi..i need your help as i am trying to connect my asp.net web app  to QuickBooks Online Account.I want to sync single data to my quickbooks online account.so can you help me in this by plotting a layout of the whole process or mechanism involved to perform this.What i am interested is that when i click a button then some of the selected data should be Synced to the QBO.so can you tell me the mechanism?

**Comment by nimisha84** [comment]
@MohitSingh1001 - Created a support ticket for you and will reply on that. Please log any API issue through your developer.intuit.com account->help. We do not have support for direct emails on personal email ids.

**Comment by MohitSingh1001** [comment]
Thank You Nimisha .. please share the link to support ticket you have
created. on my account section i cant see the ticket in support ticket.
